git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
go get -u github.com/bradfitz/goimports
go get -u github.com/jstemmer/gotags
go get -u github.com/golang/lint/golint
go get -u github.com/golang/lint/golint
go get -u code.google.com/p/rog-go/exp/cmd/godef
go get -u github.com/nsf/gocode
go get -u code.google.com/p/rog-go/exp/cmd/godef
go get -u github.com/jstemmer/gotags
